[tool.poetry]
name = "prism-api"
version = "0.1.0"
description = "AI-driven knowledge management platform"
authors = ["hwuiwon <hwuiwon.kim@gmail.com>"]
readme = "README.md"
packages = []

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.100.1"
llama-index = "^0.7.16"
python-dotenv = "^1.0.0"
boto3 = "^1.28.16"
tika = "^2.6.0"
logging = "^0.4.9.6"
uvicorn = "^0.23.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
